/* Propensity training Mart 

dba.sp_drop_table 'Decisioning','Propensity_Model_Mart_Training'
dba.sp_create_table 'Decisioning','Propensity_Model_Mart_Training',
  'Base_Dt date default	null,'
||'account_number varchar (20) default	null,'
||'Subs_Year smallint default	null,'
||'Subs_Week_Of_Year smallint default	null,'
||'Subs_Quarter_Of_Year tinyint default	null,'
||'Subs_Week_And_Year int default	null,'
||'DTV_Active tinyint default	0,'
||'DTV_Status_Code varchar (10) default	null,'
||'DTV_Product_Holding varchar (80) default	null,'
||'BB_Active tinyint default	0,'
||'BB_Status_Code varchar (10) default	null,'
||'BB_Product_Holding varchar (80) default	null,'
||'Sports_Active tinyint default	0,'
||'Sports_Status_Code varchar (10) default	null,'
||'Sports_Product_Holding varchar (80) default	null,'
||'Sports_Product_Count tinyint default	0,'
||'Movies_Active tinyint default	0,'
||'Movies_Status_Code varchar (10) default	null,'
||'Movies_Product_Holding varchar (80) default	null,'
||'Movies_Product_Count tinyint default	0,'
||'MS_Active tinyint default	0,'
||'MS_Status_Code varchar (10) default	null,'
||'MS_Product_Holding varchar (80) default	null,'
||'SGE_Active tinyint default	0,'
||'SGE_Status_Code varchar (10) default	null,'
||'SGE_Product_Holding varchar (80) default	null,'
||'HD_Active tinyint default	0,'
||'HD_Status_Code varchar (10) default	null,'
||'HD_Product_Holding varchar (80) default	null,'
||'Sky_Box_Sets_Active tinyint default	0,'
||'Sky_Box_Sets_Status_Code varchar (10) default	null,'
||'Sky_Box_Sets_Product_Holding varchar (80) default	null,'
||'UOD_Active tinyint default	0,'
||'UOD_Status_Code varchar (10) default	null,'
||'UOD_Product_Holding varchar (80) default	null,'
||'DTV_1st_Activation_Dt date default	null,'
||'DTV_Last_Activation_Dt date default	null,'
||'DTV_Activations_In_Last_1D tinyint default	0,'
||'DTV_Activations_In_Last_30D tinyint default	0,'
||'DTV_Activations_In_Last_90D tinyint default	0,'
||'DTV_Activations_In_Last_180D tinyint default	0,'
||'DTV_Activations_In_Last_1Yr tinyint default	0,'
||'DTV_Activations_In_Last_3Yr tinyint default	0,'
||'DTV_Activations_In_Last_5Yr tinyint default	0,'
||'DTV_Activations_Ever tinyint default	0,'
||'DTV_Activations_In_Next_7D tinyint default	0,'
||'DTV_Activations_In_Next_30D tinyint default	0,'
||'DTV_NewCust_Actv_In_Lt_1D tinyint default	0,'
||'DTV_NewCust_Actv_In_Lt_30D tinyint default	0,'
||'DTV_NewCust_Actv_In_Lt_90D tinyint default	0,'
||'DTV_NewCust_Actv_In_Lt_180D tinyint default	0,'
||'DTV_NewCust_Actv_In_Lt_1Yr tinyint default	0,'
||'DTV_NewCust_Actv_In_Lt_3Yr tinyint default	0,'
||'DTV_NewCust_Actv_In_Lt_5Yr tinyint default	0,'
||'DTV_NewCust_Activations_Ever tinyint default	0,'
||'DTV_NewCust_Actv_In_Nx_7D tinyint default	0,'
||'DTV_NewCust_Actv_In_Nx_30D tinyint default	0,'
||'DTV_Reinstates_In_Last_1D tinyint default	0,'
||'DTV_Reinstates_In_Last_30D tinyint default	0,'
||'DTV_Reinstates_In_Last_90D tinyint default	0,'
||'DTV_Reinstates_In_Last_180D tinyint default	0,'
||'DTV_Reinstates_In_Last_1Yr tinyint default	0,'
||'DTV_Reinstates_In_Last_3Yr tinyint default	0,'
||'DTV_Reinstates_In_Last_5Yr tinyint default	0,'
||'DTV_Reinstates_Ever tinyint default	0,'
||'DTV_Reinstates_In_Next_7D tinyint default	0,'
||'DTV_Reinstates_In_Next_30D tinyint default	0,'
||'DTV_PO_Reinstates_In_Last_1D tinyint default	0,'
||'DTV_PO_Reinstates_In_Last_30D tinyint default	0,'
||'DTV_PO_Reinstates_In_Last_90D tinyint default	0,'
||'DTV_PO_Reinstates_In_Last_180D tinyint default	0,'
||'DTV_PO_Reinstates_In_Last_1Yr tinyint default	0,'
||'DTV_PO_Reinstates_In_Last_3Yr tinyint default	0,'
||'DTV_PO_Reinstates_In_Last_5Yr tinyint default	0,'
||'DTV_PO_Reinstates_Ever tinyint default	0,'
||'DTV_PO_Reinstates_In_Next_7D tinyint default	0,'
||'DTV_PO_Reinstates_In_Next_30D tinyint default	0,'
||'DTV_SC_Reinstates_In_Last_1D tinyint default	0,'
||'DTV_SC_Reinstates_In_Last_30D tinyint default	0,'
||'DTV_SC_Reinstates_In_Last_90D tinyint default	0,'
||'DTV_SC_Reinstates_In_Last_180D tinyint default	0,'
||'DTV_SC_Reinstates_In_Last_1Yr tinyint default	0,'
||'DTV_SC_Reinstates_In_Last_3Yr tinyint default	0,'
||'DTV_SC_Reinstates_In_Last_5Yr tinyint default	0,'
||'DTV_SC_Reinstates_Ever tinyint default	0,'
||'DTV_SC_Reinstates_In_Next_7D tinyint default	0,'
||'DTV_SC_Reinstates_In_Next_30D tinyint default	0,'
||'DTV_PO_Winbacks_In_Last_1D tinyint default	0,'
||'DTV_PO_Winbacks_In_Last_30D tinyint default	0,'
||'DTV_PO_Winbacks_In_Last_90D tinyint default	0,'
||'DTV_PO_Winbacks_In_Last_180D tinyint default	0,'
||'DTV_PO_Winbacks_In_Last_1Yr tinyint default	0,'
||'DTV_PO_Winbacks_In_Last_3Yr tinyint default	0,'
||'DTV_PO_Winbacks_In_Last_5Yr tinyint default	0,'
||'DTV_PO_Winbacks_Ever tinyint default	0,'
||'DTV_PO_Winbacks_In_Next_7D tinyint default	0,'
||'DTV_PO_Winbacks_In_Next_30D tinyint default	0,'
||'DTV_SC_Winbacks_In_Last_1D tinyint default	0,'
||'DTV_SC_Winbacks_In_Last_30D tinyint default	0,'
||'DTV_SC_Winbacks_In_Last_90D tinyint default	0,'
||'DTV_SC_Winbacks_In_Last_180D tinyint default	0,'
||'DTV_SC_Winbacks_In_Last_1Yr tinyint default	0,'
||'DTV_SC_Winbacks_In_Last_3Yr tinyint default	0,'
||'DTV_SC_Winbacks_In_Last_5Yr tinyint default	0,'
||'DTV_SC_Winbacks_Ever tinyint default	0,'
||'DTV_SC_Winbacks_In_Next_7D tinyint default	0,'
||'DTV_SC_Winbacks_In_Next_30D tinyint default	0,'
||'BB_1st_Activation_Dt date default	null,'
||'BB_Last_Activation_Dt date default	null,'
||'BB_Subscriber_Actv_In_Lt_1D tinyint default	0,'
||'BB_Subscriber_Actv_In_Lt_30D tinyint default	0,'
||'BB_Subscriber_Actv_In_Lt_90D tinyint default	0,'
||'BB_Subscriber_Actv_In_Lt_180D tinyint default	0,'
||'BB_Subscriber_Actv_In_Lt_1Yr tinyint default	0,'
||'BB_Subscriber_Actv_In_Lt_3Yr tinyint default	0,'
||'BB_Subscriber_Actv_In_Lt_5Yr tinyint default	0,'
||'BB_Subscriber_Activations_Ever tinyint default	0,'
||'BB_Subscriber_Actv_In_Nx_7D tinyint default	0,'
||'BB_Subscriber_Actv_In_Nx_30D tinyint default	0,'
||'BB_Subscription_Actv_In_Lt_1D tinyint default	0,'
||'BB_Subscription_Actv_In_Lt_30D tinyint default	0,'
||'BB_Subscription_Actv_In_Lt_90D tinyint default	0,'
||'BB_Subscription_Actv_In_Lt_180D tinyint default	0,'
||'BB_Subscription_Actv_In_Lt_1Yr tinyint default	0,'
||'BB_Subscription_Actv_In_Lt_3Yr tinyint default	0,'
||'BB_Subscription_Actv_In_Lt_5Yr tinyint default	0,'
||'BB_Subscription_Activations_Ever tinyint default	0,'
||'BB_Subscription_Actv_In_Nx_7D tinyint default	0,'
||'BB_Subscription_Actv_In_Nx_30D tinyint default	0,'
||'DTV_1st_Churn_Dt date default	null,'
||'DTV_Last_Churn_Dt date default	null,'
||'DTV_1st_CusCan_Churn_Dt date default	null,'
||'DTV_Last_CusCan_Churn_Dt date default	null,'
||'DTV_1st_SysCan_Churn_Dt date default	null,'
||'DTV_Last_SysCan_Churn_Dt date default	null,'
||'DTV_Churns_In_Last_1D smallint default	0,'
||'DTV_Churns_In_Last_30D smallint default	0,'
||'DTV_Churns_In_Last_90D smallint default	0,'
||'DTV_Churns_In_Last_180D smallint default	0,'
||'DTV_Churns_In_Last_1Yr smallint default	0,'
||'DTV_Churns_In_Last_3Yr smallint default	0,'
||'DTV_Churns_In_Last_5Yr smallint default	0,'
||'DTV_Churns_Ever smallint default	0,'
||'DTV_Churns_In_Next_7D smallint default	0,'
||'DTV_Churns_In_Next_30D smallint default	0,'
||'DTV_CusCan_Churns_In_Last_1D smallint default	0,'
||'DTV_CusCan_Churns_In_Last_30D smallint default	0,'
||'DTV_CusCan_Churns_In_Last_90D smallint default	0,'
||'DTV_CusCan_Churns_In_Last_180D smallint default	0,'
||'DTV_CusCan_Churns_In_Last_1Yr smallint default	0,'
||'DTV_CusCan_Churns_In_Last_3Yr smallint default	0,'
||'DTV_CusCan_Churns_In_Last_5Yr smallint default	0,'
||'DTV_CusCan_Churns_Ever smallint default	0,'
||'DTV_CusCan_Churns_In_Next_7D smallint default	0,'
||'DTV_CusCan_Churns_In_Next_30D smallint default	0,'
||'DTV_SysCan_Churns_In_Last_1D smallint default	0,'
||'DTV_SysCan_Churns_In_Last_30D smallint default	0,'
||'DTV_SysCan_Churns_In_Last_90D smallint default	0,'
||'DTV_SysCan_Churns_In_Last_180D smallint default	0,'
||'DTV_SysCan_Churns_In_Last_1Yr smallint default	0,'
||'DTV_SysCan_Churns_In_Last_3Yr smallint default	0,'
||'DTV_SysCan_Churns_In_Last_5Yr smallint default	0,'
||'DTV_SysCan_Churns_Ever smallint default	0,'
||'DTV_SysCan_Churns_In_Next_7D smallint default	0,'
||'DTV_SysCan_Churns_In_Next_30D smallint default	0,'
||'DTV_PO_Cancellations_In_Last_1D smallint default	0,'
||'DTV_PO_Cancellations_In_Last_30D smallint default	0,'
||'DTV_PO_Cancellations_In_Last_90D smallint default	0,'
||'DTV_PO_Cancellations_In_Lt_180D smallint default	0,'
||'DTV_PO_Cancellations_In_Last_1Yr smallint default	0,'
||'DTV_PO_Cancellations_In_Last_3Yr smallint default	0,'
||'DTV_PO_Cancellations_In_Last_5Yr smallint default	0,'
||'DTV_PO_Cancellations_Ever smallint default	0,'
||'DTV_PO_Cancellations_In_Next_7D smallint default	0,'
||'DTV_PO_Cancellations_In_Next_30D smallint default	0,'
||'DTV_SameDayCancels_In_Last_1D smallint default	0,'
||'DTV_SameDayCancels_In_Last_30D smallint default	0,'
||'DTV_SameDayCancels_In_Last_90D smallint default	0,'
||'DTV_SameDayCancels_In_Last_180D smallint default	0,'
||'DTV_SameDayCancels_In_Last_1Yr smallint default	0,'
||'DTV_SameDayCancels_In_Last_3Yr smallint default	0,'
||'DTV_SameDayCancels_In_Last_5Yr smallint default	0,'
||'DTV_SameDayCancels_Ever smallint default	0,'
||'DTV_SameDayCancels_In_Next_7D smallint default	0,'
||'DTV_SameDayCancels_In_Next_30D smallint default	0,'
||'BB_1st_Churn_Dt date default	null,'
||'BB_Last_Churn_Dt date default	null,'
||'BB_Churns_In_Last_1D tinyint default	0,'
||'BB_Churns_In_Last_30D tinyint default	0,'
||'BB_Churns_In_Last_90D tinyint default	0,'
||'BB_Churns_In_Last_180D tinyint default	0,'
||'BB_Churns_In_Last_1Yr tinyint default	0,'
||'BB_Churns_In_Last_3Yr tinyint default	0,'
||'BB_Churns_In_Last_5Yr tinyint default	0,'
||'BB_Churns_Ever tinyint default	0,'
||'BB_Churns_In_Next_7D tinyint default	0,'
||'BB_Churns_In_Next_30D tinyint default	0,'
||'DTV_1st_Pending_Cancel_Dt date default	null,'
||'DTV_Last_Pending_Cancel_Dt date default	null,'
||'DTV_Last_PC_Effective_To_Dt date default	null,'
||'DTV_Last_PC_Next_Status_Code varchar (10) default	null,'
||'DTV_Lt_PC_Future_Sub_Eff_Dt date default	null,'
||'DTV_Next_Pending_Cancel_Dt date default	null,'
||'DTV_Next_PC_Effective_To_Dt date default	null,'
||'DTV_Next_PC_Next_Status_Code varchar (10) default	null,'
||'DTV_Nx_PC_Future_Sub_Eff_Dt date default	null,'
||'DTV_1st_Active_Block_Dt date default	null,'
||'DTV_Last_Active_Block_Dt date default	null,'
||'DTV_Last_AB_Effective_To_Dt date default	null,'
||'DTV_Last_AB_Next_Status_Code varchar (10) default	null,'
||'DTV_Lt_AB_Future_Sub_Eff_Dt date default	null,'
||'DTV_Next_Active_Block_Dt date default	null,'
||'DTV_Next_AB_Effective_To_Dt date default	null,'
||'DTV_Next_AB_Next_Status_Code varchar (10) default	null,'
||'DTV_Nx_AB_Future_Sub_Eff_Dt date default	null,'
||'DTV_PCs_In_Last_1D tinyint default	0,'
||'DTV_PCs_In_Last_30D tinyint default	0,'
||'DTV_PCs_In_Last_90D tinyint default	0,'
||'DTV_PCs_In_Last_180D tinyint default	0,'
||'DTV_PCs_In_Last_1Yr tinyint default	0,'
||'DTV_PCs_In_Last_3Yr tinyint default	0,'
||'DTV_PCs_In_Last_5Yr tinyint default	0,'
||'DTV_PCs_Ever tinyint default	0,'
||'DTV_PCs_In_Next_7D tinyint default	0,'
||'DTV_PCs_In_Next_30D tinyint default	0,'
||'DTV_ABs_In_Last_1D tinyint default	0,'
||'DTV_ABs_In_Last_30D tinyint default	0,'
||'DTV_ABs_In_Last_90D tinyint default	0,'
||'DTV_ABs_In_Last_180D tinyint default	0,'
||'DTV_ABs_In_Last_1Yr tinyint default	0,'
||'DTV_ABs_In_Last_3Yr tinyint default	0,'
||'DTV_ABs_In_Last_5Yr tinyint default	0,'
||'DTV_ABs_Ever tinyint default	0,'
||'DTV_ABs_In_Next_7D tinyint default	0,'
||'DTV_ABs_In_Next_30D tinyint default	0,'
||'DTV_PC_Reactivations_In_Last_1D tinyint default	0,'
||'DTV_PC_Reactivations_In_Last_30D tinyint default	0,'
||'DTV_PC_Reactivations_In_Last_90D tinyint default	0,'
||'DTV_PC_Reactivations_In_Lt_180D tinyint default	0,'
||'DTV_PC_Reactivations_In_Last_1Yr tinyint default	0,'
||'DTV_PC_Reactivations_In_Last_3Yr tinyint default	0,'
||'DTV_PC_Reactivations_In_Last_5Yr tinyint default	0,'
||'DTV_PC_Reactivations_Ever tinyint default	0,'
||'DTV_PC_Reactivations_In_Next_7D tinyint default	0,'
||'DTV_PC_Reactivations_In_Next_30D tinyint default	0,'
||'DTV_AB_Reactivations_In_Last_1D tinyint default	0,'
||'DTV_AB_Reactivations_In_Last_30D tinyint default	0,'
||'DTV_AB_Reactivations_In_Last_90D tinyint default	0,'
||'DTV_AB_Reactivations_In_Lt_180D tinyint default	0,'
||'DTV_AB_Reactivations_In_Last_1Yr tinyint default	0,'
||'DTV_AB_Reactivations_In_Last_3Yr tinyint default	0,'
||'DTV_AB_Reactivations_In_Last_5Yr tinyint default	0,'
||'DTV_AB_Reactivations_Ever tinyint default	0,'
||'DTV_AB_Reactivations_In_Next_7D tinyint default	0,'
||'DTV_AB_Reactivations_In_Next_30D tinyint default	0,'
||'DTV_PC_To_ABs_In_Last_1D tinyint default	0,'
||'DTV_PC_To_ABs_In_Last_30D tinyint default	0,'
||'DTV_PC_To_ABs_In_Last_90D tinyint default	0,'
||'DTV_PC_To_ABs_In_Last_180D tinyint default	0,'
||'DTV_PC_To_ABs_In_Last_1Yr tinyint default	0,'
||'DTV_PC_To_ABs_In_Last_3Yr tinyint default	0,'
||'DTV_PC_To_ABs_In_Last_5Yr tinyint default	0,'
||'DTV_PC_To_ABs_Ever tinyint default	0,'
||'DTV_PC_To_ABs_In_Next_7D tinyint default	0,'
||'DTV_PC_To_ABs_In_Next_30D tinyint default	0,'
||'BB_1st_Enter_SysCan_Dt date default	null,'
||'BB_Last_Enter_SysCan_Dt date default	null,'
||'BB_1st_Enter_CusCan_Dt date default	null,'
||'BB_Last_Enter_CusCan_Dt date default	null,'
||'BB_1st_Enter_HM_Dt date default	null,'
||'BB_Last_Enter_HM_Dt date default	null,'
||'BB_1st_Enter_3rd_Party_Dt date default	null,'
||'BB_Last_Enter_3rd_Party_Dt date default	null,'
||'BB_Enter_SysCan_In_Last_1D tinyint default	0,'
||'BB_Enter_SysCan_In_Last_30D tinyint default	0,'
||'BB_Enter_SysCan_In_Last_90D tinyint default	0,'
||'BB_Enter_SysCan_In_Last_180D tinyint default	0,'
||'BB_Enter_SysCan_In_Last_1Yr tinyint default	0,'
||'BB_Enter_SysCan_In_Last_3Yr tinyint default	0,'
||'BB_Enter_SysCan_In_Last_5Yr tinyint default	0,'
||'BB_Enter_SysCan_Ever tinyint default	0,'
||'BB_Enter_SysCan_In_Next_7D tinyint default	0,'
||'BB_Enter_SysCan_In_Next_30D tinyint default	0,'
||'BB_Enter_CusCan_In_Last_1D tinyint default	0,'
||'BB_Enter_CusCan_In_Last_30D tinyint default	0,'
||'BB_Enter_CusCan_In_Last_90D tinyint default	0,'
||'BB_Enter_CusCan_In_Last_180D tinyint default	0,'
||'BB_Enter_CusCan_In_Last_1Yr tinyint default	0,'
||'BB_Enter_CusCan_In_Last_3Yr tinyint default	0,'
||'BB_Enter_CusCan_In_Last_5Yr tinyint default	0,'
||'BB_Enter_CusCan_Ever tinyint default	0,'
||'BB_Enter_CusCan_In_Next_7D tinyint default	0,'
||'BB_Enter_CusCan_In_Next_30D tinyint default	0,'
||'BB_Enter_HM_In_Last_1D tinyint default	0,'
||'BB_Enter_HM_In_Last_30D tinyint default	0,'
||'BB_Enter_HM_In_Last_90D tinyint default	0,'
||'BB_Enter_HM_In_Last_180D tinyint default	0,'
||'BB_Enter_HM_In_Last_1Yr tinyint default	0,'
||'BB_Enter_HM_In_Last_3Yr tinyint default	0,'
||'BB_Enter_HM_In_Last_5Yr tinyint default	0,'
||'BB_Enter_HM_Ever tinyint default	0,'
||'BB_Enter_HM_In_Next_7D tinyint default	0,'
||'BB_Enter_HM_In_Next_30D tinyint default	0,'
||'BB_Enter_3rd_Party_In_Last_1D tinyint default	0,'
||'BB_Enter_3rd_Party_In_Last_30D tinyint default	0,'
||'BB_Enter_3rd_Party_In_Last_90D tinyint default	0,'
||'BB_Enter_3rd_Party_In_Last_180D tinyint default	0,'
||'BB_Enter_3rd_Party_In_Last_1Yr tinyint default	0,'
||'BB_Enter_3rd_Party_In_Last_3Yr tinyint default	0,'
||'BB_Enter_3rd_Party_In_Last_5Yr tinyint default	0,'
||'BB_Enter_3rd_Party_Ever tinyint default	0,'
||'BB_Enter_3rd_Party_In_Next_7D tinyint default	0,'
||'BB_Enter_3rd_Party_In_Next_30D tinyint default	0,'
||'cb_key_household bigint default	null,'
||'Country varchar (3) default	null,'
||'Age int default	null,'
||'Home_Owner_Status varchar (30) default	null,'
||'h_affluence varchar (50) default	null,'
||'h_age_coarse varchar (10) default	null,'
||'h_age_fine varchar (10) default	null,'
||'h_equivalised_income_band varchar (30) default	null,'
||'h_equivalised_income_value decimal (20) default	null,'
||'financial_strategy varchar (50) default	null,'
||'h_household_composition varchar (50) default	null,'
||'h_property_type varchar (50) default	null,'
||'h_residence_type varchar (50) default	null,'
||'h_income_band varchar (30) default	null,'
||'h_income_value decimal (20) default	null,'
||'h_family_lifestage varchar (50) default	null,'
||'h_mosaic_group varchar (50) default	null,'
||'h_number_of_adults smallint default	0,'
||'h_number_of_bedrooms smallint default	0,'
||'h_number_of_children_in_hh smallint default	0,'
||'h_presence_of_child_aged_0_4 varchar (10) default	null,'
||'h_presence_of_child_aged_5_11 varchar (10) default	null,'
||'h_presence_of_child_aged_12_17 varchar (10) default	null,'
||'h_prsnc_of_yng_person_at_address varchar (10) default	null,'
||'p_true_touch_group varchar (50) default	null,'
||'p_true_touch_type smallint default	0,'
||'cb_address_postcode_area varchar (4) default	null,'
||'cb_address_postcode_incode varchar (4) default	null,'
||'cb_address_postcode_outcode varchar (4) default	null,'
||'cb_address_postcode_sector varchar (6) default	null,'
||'cb_address_town varchar (30) default	null,'
||'cb_address_county varchar (30) default	null,'
||'skyfibre_enabled varchar (1) default	null,'
||'skyfibre_enabled_date date default	null,'
||'skyfibre_enabled_perc decimal (10) default	null,'
||'skyfibre_estimated_enabled_date date default	null,'
||'skyfibre_planned_perc decimal (10) default	null,'
||'max_speed_uplift decimal (8) default	null,'
||'_1st_TA_dt date default	null,'
||'_1st_TA_reason varchar (255) default	null,'
||'_1st_TA_outcome varchar (255) default	null,'
||'_1st_TA_site varchar (255) default	null,'
||'last_TA_dt date default	null,'
||'last_TA_reason varchar (255) default	null,'
||'last_TA_outcome varchar (255) default	null,'
||'last_TA_site varchar (255) default	null,'
||'_1st_TA_save_dt date default	null,'
||'last_TA_save_dt date default	null,'
||'_1st_TA_nonsave_dt date default	null,'
||'last_TA_nonsave_dt date default	null,'
||'TAs_in_next_30d int default	null,'
||'TAs_in_next_7d int default	null,'
||'TAs_in_last_24hrs int default	null,'
||'TAs_in_last_7d int default	null,'
||'TAs_in_last_14d int default	null,'
||'TAs_in_last_30d int default	null,'
||'TAs_in_last_60d int default	null,'
||'TAs_in_last_90d int default	null,'
||'TAs_in_last_12m int default	null,'
||'TAs_in_last_24m int default	null,'
||'TAs_in_last_36m int default	null,'
||'TA_saves_in_next_30d int default	null,'
||'TA_saves_in_next_7d int default	null,'
||'TA_saves_in_last_24hrs int default	null,'
||'TA_saves_in_last_7d int default	null,'
||'TA_saves_in_last_14d int default	null,'
||'TA_saves_in_last_30d int default	null,'
||'TA_saves_in_last_60d int default	null,'
||'TA_saves_in_last_90d int default	null,'
||'TA_saves_in_last_12m int default	null,'
||'TA_saves_in_last_24m int default	null,'
||'TA_saves_in_last_36m int default	null,'
||'TA_nonsaves_in_next_30d int default	null,'
||'TA_nonsaves_in_next_7d int default	null,'
||'TA_nonsaves_in_last_24hrs int default	null,'
||'TA_nonsaves_in_last_7d int default	null,'
||'TA_nonsaves_in_last_14d int default	null,'
||'TA_nonsaves_in_last_30d int default	null,'
||'TA_nonsaves_in_last_60d int default	null,'
||'TA_nonsaves_in_last_90d int default	null,'
||'TA_nonsaves_in_last_12m int default	null,'
||'TA_nonsaves_in_last_24m int default	null,'
||'TA_nonsaves_in_last_36m int default	null,'
||'BB_Provider varchar (20) default	null,'
||'Country_Name varchar (150) default	null,'
||'Government_Region varchar (255) default	null,'
||'Local_Authority_Name varchar (255) default	null,'
||'Exchange_Name varchar (100) default	null,'
||'Exchange_Status varchar (10) default	null,'
||'ADSL_Enabled varchar (1) default	null,'
||'Broadband_Average_Demand decimal (30) default	null,'
||'BT_Consumer_Market_Share decimal (30) default	null,'
||'Sky_Consumer_Market_Share decimal (30) default	null,'
||'Virgin_Consumer_Market_Share decimal (30) default	null,'
||'TalkTalk_Consumer_Market_Share decimal (30) default	null,'
||'Cable_Postcode varchar (1) default	null,'
||'Superfast_Available_End_2013 decimal (30) default	null,'
||'Superfast_Available_End_2014 decimal (30) default	null,'
||'Superfast_Available_End_2015 decimal (30) default	null,'
||'Superfast_Available_End_2016 decimal (30) default	null,'
||'Superfast_Available_End_2017 decimal (30) default	null,'
||'Throughput_Speed decimal (30) default	null,'
||'_1st_OTT_Purchased_Dt date default	null,'
||'Last_OTT_Purchased_Dt date default	null,'
||'Next_OTT_Purchased_Dt date default	null,'
||'OTT_Purchases_In_Next_30d int default	null,'
||'OTT_Purchases_In_Next_7d int default	null,'
||'OTT_Purchases_In_Next_1d int default	null,'
||'OTT_Purchases_In_Last_1d int default	null,'
||'OTT_Purchases_In_Last_7d int default	null,'
||'OTT_Purchases_In_Last_30d int default	null,'
||'OTT_Purchases_In_Last_60d int default	null,'
||'OTT_Purchases_In_Last_90d int default	null,'
||'OTT_Purchases_In_Last_180d int default	null,'
||'OTT_Purchases_In_Last_1yr int default	null,'
||'OTT_Purchases_In_Last_3yr int default	null,'
||'OTT_Purchases_Ever int default	null,'
||'_1st_Movies_Purchased_Dt date default	null,'
||'Last_Movies_Purchased_Dt date default	null,'
||'Next_Movies_Purchased_Dt date default	null,'
||'Movies_Purchases_In_Next_30d int default	null,'
||'Movies_Purchases_In_Next_7d int default	null,'
||'Movies_Purchases_In_Next_1d int default	null,'
||'Movies_Purchases_In_Last_1d int default	null,'
||'Movies_Purchases_In_Last_7d int default	null,'
||'Movies_Purchases_In_Last_30d int default	null,'
||'Movies_Purchases_In_Last_60d int default	null,'
||'Movies_Purchases_In_Last_90d int default	null,'
||'Movies_Purchases_In_Last_180d int default	null,'
||'Movies_Purchases_In_Last_1yr int default	null,'
||'Movies_Purchases_In_Last_3yr int default	null,'
||'Movies_Purchases_Ever int default	null,'
||'DTV_Curr_Contract_Start_Dt date default	null,'
||'DTV_Curr_Contract_Intnd_End_Dt date default	null,'
||'DTV_Prev_Contract_Start_Dt date default	null,'
||'DTV_Prev_Contract_Intnd_End_Dt date default	null,'
||'DTV_Prev_Contract_Actual_End_Dt date default	null,'
||'BB_Curr_Contract_Start_Dt date default	null,'
||'BB_Curr_Contract_Intended_End_Dt date default	null,'
||'BB_Prev_Contract_Start_Dt date default	null,'
||'BB_Prev_Contract_Intended_End_Dt date default	null,'
||'BB_Prev_Contract_Actual_End_Dt date default	null,'
||'Prev_Offer_Start_Dt_DTV date default	null,'
||'Prev_Offer_Intended_end_Dt_DTV date default	null,'
||'Prev_Offer_Actual_End_Dt_DTV date default	null,'
||'Prev_Offer_ID_DTV int default	null,'
||'Prev_Offer_Description_DTV varchar (100) default	null,'
||'Prev_Offer_Length_DTV varchar (50) default	null,'
||'Prev_Offer_Amount_DTV decimal (20) default	null,'
||'Curr_Offer_Start_Dt_DTV date default	null,'
||'Curr_Offer_Intended_end_Dt_DTV date default	null,'
||'Curr_Offer_Actual_End_Dt_DTV date default	null,'
||'Curr_Offer_ID_DTV int default	null,'
||'Curr_Offer_Description_DTV varchar (100) default	null,'
||'Curr_Offer_Length_DTV varchar (50) default	null,'
||'Curr_Offer_Amount_DTV decimal (20) default	null,'
||'_1st_Offer_Applied_Dt_DTV date default	null,'
||'Last_Offer_Applied_Dt_DTV date default	null,'
||'Offers_Applied_Lst_1D_DTV smallint default	0,'
||'Offers_Applied_Lst_7D_DTV smallint default	0,'
||'Offers_Applied_Lst_30D_DTV smallint default	0,'
||'Offers_Applied_Lst_90D_DTV smallint default	0,'
||'Offers_Applied_Lst_12M_DTV smallint default	0,'
||'Offers_Applied_Lst_24M_DTV smallint default	0,'
||'Offers_Applied_Lst_36M_DTV smallint default	0,'
||'Offers_Applied_Next_7D_DTV smallint default	0,'
||'Offers_Applied_Next_30D_DTV smallint default	0,'
||'Offers_Applied_Ever_DTV smallint default	0,'
||'Prev_Offer_Start_Dt_BB date default	null,'
||'Prev_Offer_Intended_end_Dt_BB date default	null,'
||'Prev_Offer_Actual_End_Dt_BB date default	null,'
||'Prev_Offer_ID_BB int default	null,'
||'Prev_Offer_Description_BB varchar (100) default	null,'
||'Prev_Offer_Length_BB varchar (50) default	null,'
||'Prev_Offer_Amount_BB decimal (20) default	null,'
||'Curr_Offer_Start_Dt_BB date default	null,'
||'Curr_Offer_Intended_end_Dt_BB date default	null,'
||'Curr_Offer_Actual_End_Dt_BB date default	null,'
||'Curr_Offer_ID_BB int default	null,'
||'Curr_Offer_Description_BB varchar (100) default	null,'
||'Curr_Offer_Length_BB varchar (50) default	null,'
||'Curr_Offer_Amount_BB decimal (20) default	null,'
||'_1st_Offer_Applied_Dt_BB date default	null,'
||'Last_Offer_Applied_Dt_BB date default	null,'
||'Offers_Applied_Lst_1D_BB smallint default	0,'
||'Offers_Applied_Lst_7D_BB smallint default	0,'
||'Offers_Applied_Lst_30D_BB smallint default	0,'
||'Offers_Applied_Lst_90D_BB smallint default	0,'
||'Offers_Applied_Lst_12M_BB smallint default	0,'
||'Offers_Applied_Lst_24M_BB smallint default	0,'
||'Offers_Applied_Lst_36M_BB smallint default	0,'
||'Offers_Applied_Next_7D_BB smallint default	0,'
||'Offers_Applied_Next_30D_BB smallint default	0,'
||'Offers_Applied_Ever_BB smallint default	0,'
||'SGE_1st_Activation_Dt date default	null,'
||'SGE_Last_Activation_Dt date default	null,'
||'SGE_NewCust_Activations_In_Last_1D tinyint default	0,'
||'SGE_NewCust_Activations_In_Last_7D tinyint default	0,'
||'SGE_NewCust_Activations_In_Last_30D tinyint default	0,'
||'SGE_NewCust_Activations_In_Last_90D tinyint default	0,'
||'SGE_NewCust_Activations_In_Last_180D tinyint default	0,'
||'SGE_NewCust_Activations_In_Last_1Yr tinyint default	0,'
||'SGE_NewCust_Activations_In_Last_3Yr tinyint default	0,'
||'SGE_NewCust_Activations_In_Last_5Yr tinyint default	0,'
||'SGE_NewCust_Activations_Ever tinyint default	0,'
||'SGE_NewCust_Activations_In_Next_7D tinyint default	0,'
||'SGE_NewCust_Activations_In_Next_30D tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Last_1D tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Last_7D tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Last_30D tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Last_90D tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Last_180D tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Last_1Yr tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Last_3Yr tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Last_5Yr tinyint default	0,'
||'SGE_Existing_Customer_Activation_Ever tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Next_7D tinyint default	0,'
||'SGE_Existing_Customer_Activation_In_Next_30D tinyint default	0,'
||'SGE_Reinstatements_In_Last_1D tinyint default	0,'
||'SGE_Reinstatements_In_Last_7D tinyint default	0,'
||'SGE_Reinstatements_In_Last_30D tinyint default	0,'
||'SGE_Reinstatements_In_Last_90D tinyint default	0,'
||'SGE_Reinstatements_In_Last_180D tinyint default	0,'
||'SGE_Reinstatements_In_Last_1Yr tinyint default	0,'
||'SGE_Reinstatements_In_Last_3Yr tinyint default	0,'
||'SGE_Reinstatements_In_Last_5Yr tinyint default	0,'
||'SGE_Reinstatements_Ever tinyint default	0,'
||'SGE_Reinstatements_In_Next_7D tinyint default	0,'
||'SGE_Reinstatements_In_Next_30D tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Last_1D tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Last_7D tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Last_30D tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Last_90D tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Last_180D tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Last_1Yr tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Last_3Yr tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Last_5Yr tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_Ever tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Next_7D tinyint default	0,'
||'SGE_SC_Platform_Reinstatements_In_Next_30D tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Last_1D tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Last_7D tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Last_30D tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Last_90D tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Last_180D tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Last_1Yr tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Last_3Yr tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Last_5Yr tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_Ever tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Next_7D tinyint default	0,'
||'SGE_PO_Platform_Reinstatements_In_Next_30D tinyint default	0,'
||'NTV_Ents_Last_30D bit default 0,'
||'NTV_Ents_Last_90D bit default 0,'
||'DTV_product_holding_recode varchar (40) default	null,'
||'DTV_Last_cuscan_churn int default	null,'
||'DTV_Last_Activation int default	null,'
||'DTV_Curr_Contract_Intended_End int default	null,'
||'DTV_Curr_Contract_Start int default	null,'
||'DTV_Last_SysCan_Churn int default	null,'
||'Curr_Offer_Start_DTV int default	null,'
||'Curr_Offer_Actual_End_DTV int default	null,'
||'DTV_1st_Activation int default	null,'
||'BB_Curr_Contract_Intended_End int default	null,'
||'BB_Curr_Contract_Start int default	null,'
||'DTV_Last_Active_Block int default	null,'
||'DTV_Last_Pending_Cancel int default	null,'
||'BB_Last_Activation int default	null,'
||'_1st_TA int default	null,'
||'last_TA int default	null,'
||'_1st_TA_save int default	null,'
||'last_TA_save int default	null,'
||'_1st_TA_nonsave int default	null,'
||'last_TA_nonsave int default	null,'
||'Q_PrimaryBox tinyint default	0,'
||'UP_SkyQ tinyint default	0,'
||'Mobile_Up_Order bit default 0,'
||'Mobile_Active bit default 0,'
||'Sports_1st_Activation_Dt date default	null,'
||'Sports_Last_Activation_Dt date default	null,'
||'Sports_Activations_In_Last_1D int default	null,'
||'Sports_Activations_In_Last_30D int default	null,'
||'Sports_Activations_In_Last_90D int default	null,'
||'Sports_Activations_In_Last_180D int default	null,'
||'Sports_Activations_In_Last_1Yr int default	null,'
||'Sports_Activations_In_Last_3Yr int default	null,'
||'Sports_Activations_In_Last_5Yr int default	null,'
||'Sports_Activations_Ever int default	null,'
||'Sports_Activations_In_Next_7D int default	null,'
||'Sports_Activations_In_Next_30D int default	null,'
||'Sports_New_Adds_In_Last_1D int default	null,'
||'Sports_New_Adds_In_Last_30D int default	null,'
||'Sports_New_Adds_In_Last_90D int default	null,'
||'Sports_New_Adds_In_Last_180D int default	null,'
||'Sports_New_Adds_In_Last_1Yr int default	null,'
||'Sports_New_Adds_In_Last_3Yr int default	null,'
||'Sports_New_Adds_In_Last_5Yr int default	null,'
||'Sports_New_Adds_Ever tinyint default	0,'
||'Sports_New_Adds_In_Next_7D int default	null,'
||'Sports_New_Adds_In_Next_30D int default	null,'
||'Sports_Upgrades_In_Last_1D int default	null,'
||'Sports_Upgrades_In_Last_30D int default	null,'
||'Sports_Upgrades_In_Last_90D int default	null,'
||'Sports_Upgrades_In_Last_180D int default	null,'
||'Sports_Upgrades_In_Last_1Yr int default	null,'
||'Sports_Upgrades_In_Last_3Yr int default	null,'
||'Sports_Upgrades_In_Last_5Yr int default	null,'
||'Sports_Upgrades_Ever int default	null,'
||'Sports_Upgrades_In_Next_7D int default	null,'
||'Sports_Upgrades_In_Next_30D int default	null,'
||'Sports_Reinstates_In_Last_1D int default	null,'
||'Sports_Reinstates_In_Last_30D int default	null,'
||'Sports_Reinstates_In_Last_90D int default	null,'
||'Sports_Reinstates_In_Last_180D int default	null,'
||'Sports_Reinstates_In_Last_1Yr int default	null,'
||'Sports_Reinstates_In_Last_3Yr int default	null,'
||'Sports_Reinstates_In_Last_5Yr int default	null,'
||'Sports_Reinstates_Ever int default	null,'
||'Sports_Reinstates_In_Next_7D int default	null,'
||'Sports_Reinstates_In_Next_30D int default	null,'
||'Movies_1st_Activation_Dt date default	null,'
||'Movies_Last_Activation_Dt date default	null,'
||'Movies_Activations_In_Last_1D int default	null,'
||'Movies_Activations_In_Last_30D int default	null,'
||'Movies_Activations_In_Last_90D int default	null,'
||'Movies_Activations_In_Last_180D int default	null,'
||'Movies_Activations_In_Last_1Yr int default	null,'
||'Movies_Activations_In_Last_3Yr int default	null,'
||'Movies_Activations_In_Last_5Yr int default	null,'
||'Movies_Activations_Ever int default	null,'
||'Movies_Activations_In_Next_7D int default	null,'
||'Movies_Activations_In_Next_30D int default	null,'
||'Movies_New_Adds_In_Last_1D int default	null,'
||'Movies_New_Adds_In_Last_30D int default	null,'
||'Movies_New_Adds_In_Last_90D int default	null,'
||'Movies_New_Adds_In_Last_180D int default	null,'
||'Movies_New_Adds_In_Last_1Yr int default	null,'
||'Movies_New_Adds_In_Last_3Yr int default	null,'
||'Movies_New_Adds_In_Last_5Yr int default	null,'
||'Movies_New_Adds_Ever tinyint default	0,'
||'Movies_New_Adds_In_Next_7D int default	null,'
||'Movies_New_Adds_In_Next_30D int default	null,'
||'Movies_Upgrades_In_Last_1D int default	null,'
||'Movies_Upgrades_In_Last_30D int default	null,'
||'Movies_Upgrades_In_Last_90D int default	null,'
||'Movies_Upgrades_In_Last_180D int default	null,'
||'Movies_Upgrades_In_Last_1Yr int default	null,'
||'Movies_Upgrades_In_Last_3Yr int default	null,'
||'Movies_Upgrades_In_Last_5Yr int default	null,'
||'Movies_Upgrades_Ever int default	null,'
||'Movies_Upgrades_In_Next_7D int default	null,'
||'Movies_Upgrades_In_Next_30D int default	null,'
||'Movies_Reinstates_In_Last_1D int default	null,'
||'Movies_Reinstates_In_Last_30D int default	null,'
||'Movies_Reinstates_In_Last_90D int default	null,'
||'Movies_Reinstates_In_Last_180D int default	null,'
||'Movies_Reinstates_In_Last_1Yr int default	null,'
||'Movies_Reinstates_In_Last_3Yr int default	null,'
||'Movies_Reinstates_In_Last_5Yr int default	null,'
||'Movies_Reinstates_Ever int default	null,'
||'Movies_Reinstates_In_Next_7D int default	null,'
||'Movies_Reinstates_In_Next_30D int default	null,'
||'Sports_1st_Platform_Churn_Dt date default	null,'
||'Sports_Last_Platform_Churn_Dt date default	null,'
||'Sports_1st_Downgrade_Dt date default	null,'
||'Sports_Last_Downgrade_Dt date default	null,'
||'Sports_Platform_Churns_In_Last_1D smallint default	0,'
||'Sports_Platform_Churns_In_Last_30D smallint default	0,'
||'Sports_Platform_Churns_In_Last_90D smallint default	0,'
||'Sports_Platform_Churns_In_Last_180D smallint default	0,'
||'Sports_Platform_Churns_In_Last_1Yr smallint default	0,'
||'Sports_Platform_Churns_In_Last_3Yr smallint default	0,'
||'Sports_Platform_Churns_In_Last_5Yr smallint default	0,'
||'Sports_Platform_Churns_Ever smallint default	0,'
||'Sports_Platform_Churns_In_Next_7D smallint default	0,'
||'Sports_Platform_Churns_In_Next_30D smallint default	0,'
||'Sports_Downgrades_In_Last_1D smallint default	0,'
||'Sports_Downgrades_In_Last_30D smallint default	0,'
||'Sports_Downgrades_In_Last_90D smallint default	0,'
||'Sports_Downgrades_In_Last_180D smallint default	0,'
||'Sports_Downgrades_In_Last_1Yr smallint default	0,'
||'Sports_Downgrades_In_Last_3Yr smallint default	0,'
||'Sports_Downgrades_In_Last_5Yr smallint default	0,'
||'Sports_Downgrades_Ever smallint default	0,'
||'Sports_Downgrades_In_Next_7D smallint default	0,'
||'Sports_Downgrades_In_Next_30D smallint default	0,'
||'Movies_1st_Platform_Churn_Dt date default	null,'
||'Movies_Last_Platform_Churn_Dt date default	null,'
||'Movies_1st_Downgrade_Dt date default	null,'
||'Movies_Last_Downgrade_Dt date default	null,'
||'Movies_Platform_Churns_In_Last_1D smallint default	0,'
||'Movies_Platform_Churns_In_Last_30D smallint default	0,'
||'Movies_Platform_Churns_In_Last_90D smallint default	0,'
||'Movies_Platform_Churns_In_Last_180D smallint default	0,'
||'Movies_Platform_Churns_In_Last_1Yr smallint default	0,'
||'Movies_Platform_Churns_In_Last_3Yr smallint default	0,'
||'Movies_Platform_Churns_In_Last_5Yr smallint default	0,'
||'Movies_Platform_Churns_Ever smallint default	0,'
||'Movies_Platform_Churns_In_Next_7D smallint default	0,'
||'Movies_Platform_Churns_In_Next_30D smallint default	0,'
||'Movies_Downgrades_In_Last_1D smallint default	0,'
||'Movies_Downgrades_In_Last_30D smallint default	0,'
||'Movies_Downgrades_In_Last_90D smallint default	0,'
||'Movies_Downgrades_In_Last_180D smallint default	0,'
||'Movies_Downgrades_In_Last_1Yr smallint default	0,'
||'Movies_Downgrades_In_Last_3Yr smallint default	0,'
||'Movies_Downgrades_In_Last_5Yr smallint default	0,'
||'Movies_Downgrades_Ever smallint default	0,'
||'Movies_Downgrades_In_Next_7D smallint default	0,'
||'Movies_Downgrades_In_Next_30D smallint default	0,'
||'Prev_Offer_Start_Dt_Sports date default	null,'
||'Prev_Offer_Intended_end_Dt_Sports date default	null,'
||'Prev_Offer_Actual_End_Dt_Sports date default	null,'
||'Prev_Offer_ID_Sports int default	null,'
||'Prev_Offer_Description_Sports varchar (100) default	null,'
||'Prev_Offer_Length_Sports varchar (50) default	null,'
||'Prev_Offer_Amount_Sports decimal (20) default	null,'
||'Curr_Offer_Start_Dt_Sports date default	null,'
||'Curr_Offer_Intended_end_Dt_Sports date default	null,'
||'Curr_Offer_Actual_End_Dt_Sports date default	null,'
||'Curr_Offer_ID_Sports int default	null,'
||'Curr_Offer_Description_Sports varchar (100) default	null,'
||'Curr_Offer_Length_Sports varchar (50) default	null,'
||'Curr_Offer_Amount_Sports decimal (20) default	null,'
||'_1st_Offer_Applied_Dt_Sports date default	null,'
||'Last_Offer_Applied_Dt_Sports date default	null,'
||'Offers_Applied_Lst_1D_Sports smallint default	0,'
||'Offers_Applied_Lst_7D_Sports smallint default	0,'
||'Offers_Applied_Lst_30D_Sports smallint default	0,'
||'Offers_Applied_Lst_90D_Sports smallint default	0,'
||'Offers_Applied_Lst_12M_Sports smallint default	0,'
||'Offers_Applied_Lst_24M_Sports smallint default	0,'
||'Offers_Applied_Lst_36M_Sports smallint default	0,'
||'Offers_Applied_Next_7D_Sports smallint default	0,'
||'Offers_Applied_Next_30D_Sports smallint default	0,'
||'Offers_Applied_Ever_Sports smallint default	0,'
||'Prev_Offer_Start_Dt_Movies date default	null,'
||'Prev_Offer_Intended_end_Dt_Movies date default	null,'
||'Prev_Offer_Actual_End_Dt_Movies date default	null,'
||'Prev_Offer_ID_Movies int default	null,'
||'Prev_Offer_Description_Movies varchar (100) default	null,'
||'Prev_Offer_Length_Movies varchar (50) default	null,'
||'Prev_Offer_Amount_Movies decimal (20) default	null,'
||'Curr_Offer_Start_Dt_Movies date default	null,'
||'Curr_Offer_Intended_end_Dt_Movies date default	null,'
||'Curr_Offer_Actual_End_Dt_Movies date default	null,'
||'Curr_Offer_ID_Movies int default	null,'
||'Curr_Offer_Description_Movies varchar (100) default	null,'
||'Curr_Offer_Length_Movies varchar (50) default	null,'
||'Curr_Offer_Amount_Movies decimal (20) default	null,'
||'_1st_Offer_Applied_Dt_Movies date default	null,'
||'Last_Offer_Applied_Dt_Movies date default	null,'
||'Offers_Applied_Lst_1D_Movies smallint default	0,'
||'Offers_Applied_Lst_7D_Movies smallint default	0,'
||'Offers_Applied_Lst_30D_Movies smallint default	0,'
||'Offers_Applied_Lst_90D_Movies smallint default	0,'
||'Offers_Applied_Lst_12M_Movies smallint default	0,'
||'Offers_Applied_Lst_24M_Movies smallint default	0,'
||'Offers_Applied_Lst_36M_Movies smallint default	0,'
||'Offers_Applied_Next_7D_Movies smallint default	0,'
||'Offers_Applied_Next_30D_Movies smallint default	0,'
||'Offers_Applied_Ever_Movies smallint default	0,'
||'MS_1st_Activation_Dt date default	null,'
||'MS_Last_Activation_Dt date default	null,'
||'MS_NewCust_Activations_In_Last_1D tinyint default	0,'
||'MS_NewCust_Activations_In_Last_7D tinyint default	0,'
||'MS_NewCust_Activations_In_Last_30D tinyint default	0,'
||'MS_NewCust_Activations_In_Last_90D tinyint default	0,'
||'MS_NewCust_Activations_In_Last_180D tinyint default	0,'
||'MS_NewCust_Activations_In_Last_1Yr tinyint default	0,'
||'MS_NewCust_Activations_In_Last_3Yr tinyint default	0,'
||'MS_NewCust_Activations_In_Last_5Yr tinyint default	0,'
||'MS_NewCust_Activations_Ever tinyint default	0,'
||'MS_NewCust_Activations_In_Next_7D tinyint default	0,'
||'MS_NewCust_Activations_In_Next_30D tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Last_1D tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Last_7D tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Last_30D tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Last_90D tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Last_180D tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Last_1Yr tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Last_3Yr tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Last_5Yr tinyint default	0,'
||'MS_Existing_Customer_Activation_Ever tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Next_7D tinyint default	0,'
||'MS_Existing_Customer_Activation_In_Next_30D tinyint default	0,'
||'MS_Reinstatements_In_Last_1D tinyint default	0,'
||'MS_Reinstatements_In_Last_7D tinyint default	0,'
||'MS_Reinstatements_In_Last_30D tinyint default	0,'
||'MS_Reinstatements_In_Last_90D tinyint default	0,'
||'MS_Reinstatements_In_Last_180D tinyint default	0,'
||'MS_Reinstatements_In_Last_1Yr tinyint default	0,'
||'MS_Reinstatements_In_Last_3Yr tinyint default	0,'
||'MS_Reinstatements_In_Last_5Yr tinyint default	0,'
||'MS_Reinstatements_Ever tinyint default	0,'
||'MS_Reinstatements_In_Next_7D tinyint default	0,'
||'MS_Reinstatements_In_Next_30D tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Last_1D tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Last_7D tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Last_30D tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Last_90D tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Last_180D tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Last_1Yr tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Last_3Yr tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Last_5Yr tinyint default	0,'
||'MS_SC_Platform_Reinstatements_Ever tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Next_7D tinyint default	0,'
||'MS_SC_Platform_Reinstatements_In_Next_30D tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Last_1D tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Last_7D tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Last_30D tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Last_90D tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Last_180D tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Last_1Yr tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Last_3Yr tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Last_5Yr tinyint default	0,'
||'MS_PO_Platform_Reinstatements_Ever tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Next_7D tinyint default	0,'
||'MS_PO_Platform_Reinstatements_In_Next_30D tinyint default	0,'
||'_1st_Event_Purchased_Dt date default	null,'
||'Last_Event_Purchased_Dt date default	null,'
||'Next_Event_Purchased_Dt date default	null,'
||'Event_Purchases_In_Next_30d int default	null,'
||'Event_Purchases_In_Next_7d int default	null,'
||'Event_Purchases_In_Next_1d int default	null,'
||'Event_Purchases_In_Last_1d int default	null,'
||'Event_Purchases_In_Last_7d int default	null,'
||'Event_Purchases_In_Last_30d int default	null,'
||'Event_Purchases_In_Last_60d int default	null,'
||'Event_Purchases_In_Last_90d int default	null,'
||'Event_Purchases_In_Last_180d int default	null,'
||'Event_Purchases_In_Last_1yr int default	null,'
||'Event_Purchases_In_Last_3yr int default	null,'
||'Event_Purchases_Ever int default	null,'
||'_1st_BnK_Purchased_Dt date default	null,'
||'Last_BnK_Purchased_Dt date default	null,'
||'Next_BnK_Purchased_Dt date default	null,'
||'BnK_Purchases_In_Next_30d int default	null,'
||'BnK_Purchases_In_Next_7d int default	null,'
||'BnK_Purchases_In_Next_1d int default	null,'
||'BnK_Purchases_In_Last_1d int default	null,'
||'BnK_Purchases_In_Last_7d int default	null,'
||'BnK_Purchases_In_Last_30d int default	null,'
||'BnK_Purchases_In_Last_60d int default	null,'
||'BnK_Purchases_In_Last_90d int default	null,'
||'BnK_Purchases_In_Last_180d int default	null,'
||'BnK_Purchases_In_Last_1yr int default	null,'
||'BnK_Purchases_In_Last_3yr int default	null,'
||'BnK_Purchases_Ever int default	null,'
||'Handset_Active bit default 0,'
||'Cricket_Sports_Pref int default	null,'
||'_1st_Cricket_Pref_Registered_dt date default	null,'
||'Last_Cricket_Pref_Registered_dt date default	null,'
||'Next_Cricket_Pref_Registered_dt date default	null,'
||'Football_Sports_Pref int default	null,'
||'_1st_Football_Pref_Registered_dt date default	null,'
||'Last_Football_Pref_Registered_dt date default	null,'
||'Next_Football_Pref_Registered_dt date default	null,'
||'Rugby_Union_Sports_Pref int default	null,'
||'_1st_Rugby_Union_Pref_Registered_dt date default	null,'
||'Last_Rugby_Union_Pref_Registered_dt date default	null,'
||'Next_Rugby_Union_Pref_Registered_dt date default	null,'
||'Rugby_League_Sports_Pref int default	null,'
||'_1st_Rugby_League_Pref_Registered_dt date default	null,'
||'Last_Rugby_League_Pref_Registered_dt date default	null,'
||'Next_Rugby_League_Pref_Registered_dt date default	null,'
||'F1_Sports_Pref int default	null,'
||'_1st_F1_Pref_Registered_dt date default	null,'
||'Last_F1_Pref_Registered_dt date default	null,'
||'Next_F1_Pref_Registered_dt date default	null,'
||'Darts_Sports_Pref int default	null,'
||'_1st_Darts_Pref_Registered_dt date default	null,'
||'Last_Darts_Pref_Registered_dt date default	null,'
||'Next_Darts_Pref_Registered_dt date default	null,'
||'Tennis_Sports_Pref int default	null,'
||'_1st_Tennis_Pref_Registered_dt date default	null,'
||'Last_Tennis_Pref_Registered_dt date default	null,'
||'Next_Tennis_Pref_Registered_dt date default	null,'
||'Racing_Sports_Pref int default	null,'
||'_1st_Racing_Pref_Registered_dt date default	null,'
||'Last_Racing_Pref_Registered_dt date default	null,'
||'Next_Racing_Pref_Registered_dt date default	null,'
||'Boxing_Sports_Pref int default	null,'
||'_1st_Boxing_Pref_Registered_dt date default	null,'
||'Last_Boxing_Pref_Registered_dt date default	null,'
||'Next_Boxing_Pref_Registered_dt date default	null,'
||'Golf_Sports_Pref int default	null,'
||'_1st_Golf_Pref_Registered_dt date default	null,'
||'Last_Golf_Pref_Registered_dt date default	null,'
||'Next_Golf_Pref_Registered_dt date default	null,'
||'NFL_Sports_Pref int default	null,'
||'_1st_NFL_Pref_Registered_dt date default	null,'
||'Last_NFL_Pref_Registered_dt date default	null,'
||'Next_NFL_Pref_Registered_dt date default	null,'
||'Wrestling_Sports_Pref int default	null,'
||'_1st_Wrestling_Pref_Registered_dt date default	null,'
||'Last_Wrestling_Pref_Registered_dt date default	null,'
||'Next_Wrestling_Pref_Registered_dt date default	null,'
||'ESports_Sports_Pref int default	null,'
||'_1st_ESports_Pref_Registered_dt date default	null,'
||'Last_ESports_Pref_Registered_dt date default	null,'
||'Next_ESports_Pref_Registered_dt date default	null,'
||'GAA_Sports_Pref int default	null,'
||'_1st_GAA_Pref_Registered_dt date default	null,'
||'Last_GAA_Pref_Registered_dt date default	null,'
||'Next_GAA_Pref_Registered_dt date default	null,'
||'Motorsport_Sports_Pref int default	null,'
||'_1st_Motorsport_Pref_Registered_dt date default	null,'
||'Last_Motorsport_Pref_Registered_dt date default	null,'
||'Next_Motorsport_Pref_Registered_dt date default	null,'
||'Cycling_Sports_Pref int default	null,'
||'_1st_Cycling_Pref_Registered_dt date default	null,'
||'Last_Cycling_Pref_Registered_dt date default	null,'
||'Next_Cycling_Pref_Registered_dt date default	null,'
||'Netball_Sports_Pref int default	null,'
||'_1st_Netball_Pref_Registered_dt date default	null,'
||'Last_Netball_Pref_Registered_dt date default	null,'
||'Next_Netball_Pref_Registered_dt date default	null,'
||'_1st_SportsApp_Usage_dt date default	null,'
||'Last_SportsApp_Usage_dt date default	null,'
||'Next_SportsApp_Usage_dt date default	null,'
||'SportsApp_Sessions_In_Next_30d int default	null,'
||'SportsApp_Sessions_In_Next_7d int default	null,'
||'SportsApp_Sessions_In_Next_1d int default	null,'
||'SportsApp_Sessions_In_Last_1d int default	null,'
||'SportsApp_Sessions_In_Last_7d int default	null,'
||'SportsApp_Sessions_In_Last_30d int default	null,'
||'SportsApp_Sessions_In_Last_60d int default	null,'
||'SportsApp_Sessions_In_Last_90d int default	null,'
||'SportsApp_Sessions_In_Last_180d int default	null,'
||'SportsApp_Sessions_In_Last_1yr int default	null,'
||'SportsApp_Sessions_In_Last_3yr int default	null,'
||'SportsApp_Sessions_Ever int default	null,'
||'_1st_Completed_OD_DL_Dt date default	null,'
||'Last_Completed_OD_DL_Dt date default	null,'
||'Next_Completed_OD_DL_Dt date default	null,'
||'OD_DLs_Completed_In_Next_30d int default	null,'
||'OD_DLs_Completed_In_Next_7d int default	null,'
||'OD_DLs_Completed_In_Next_1d int default	null,'
||'OD_DLs_Completed_In_Last_1d int default	null,'
||'OD_DLs_Completed_In_Last_7d int default	null,'
||'OD_DLs_Completed_In_Last_30d int default	null,'
||'OD_DLs_Completed_In_Last_60d int default	null,'
||'OD_DLs_Completed_In_Last_90d int default	null,'
||'OD_DLs_Completed_In_Last_180d int default	null,'
||'OD_DLs_Completed_In_Last_1yr int default	null,'
||'OD_DLs_Completed_In_Last_3yr int default	null,'
||'OD_DLs_Completed_Ever int default	null,'
||'_1st_Order_Movies_Added_Dt date default	null,'
||'Last_Order_Movies_Added_Dt date default	null,'
||'Next_Order_Movies_Added_Dt date default	null,'
||'Last_Order_Movies_Product_Added varchar (80) default	null,'
||'Order_Movies_Added_In_Next_60d tinyint default	0,'
||'Order_Movies_Added_In_Next_30d tinyint default	0,'
||'Order_Movies_Added_In_Next_7d tinyint default	0,'
||'Order_Movies_Added_In_Next_24hrs tinyint default	0,'
||'Order_Movies_Added_In_Last_24hrs tinyint default	0,'
||'Order_Movies_Added_In_Last_7d tinyint default	0,'
||'Order_Movies_Added_In_Last_30d tinyint default	0,'
||'Order_Movies_Added_In_Last_60d tinyint default	0,'
||'Order_Movies_Added_In_Last_90d tinyint default	0,'
||'Order_Movies_Added_In_Last_180d tinyint default	0,'
||'Order_Movies_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_Movies_Removed_Dt date default	null,'
||'Last_Order_Movies_Removed_Dt date default	null,'
||'Next_Order_Movies_Removed_Dt date default	null,'
||'Last_Order_Movies_Product_Removed varchar (80) default	null,'
||'Order_Movies_Removed_In_Next_60d tinyint default	0,'
||'Order_Movies_Removed_In_Next_30d tinyint default	0,'
||'Order_Movies_Removed_In_Next_7d tinyint default	0,'
||'Order_Movies_Removed_In_Next_24hrs tinyint default	0,'
||'Order_Movies_Removed_In_Last_24hrs tinyint default	0,'
||'Order_Movies_Removed_In_Last_7d tinyint default	0,'
||'Order_Movies_Removed_In_Last_30d tinyint default	0,'
||'Order_Movies_Removed_In_Last_60d tinyint default	0,'
||'Order_Movies_Removed_In_Last_90d tinyint default	0,'
||'Order_Movies_Removed_In_Last_180d tinyint default	0,'
||'Order_Movies_Removed_In_Last_1yr tinyint default	0,'
||'_1st_Order_Sports_Added_Dt date default	null,'
||'Last_Order_Sports_Added_Dt date default	null,'
||'Next_Order_Sports_Added_Dt date default	null,'
||'Last_Order_Sports_Product_Added varchar (80) default	null,'
||'Order_Sports_Added_In_Next_60d tinyint default	0,'
||'Order_Sports_Added_In_Next_30d tinyint default	0,'
||'Order_Sports_Added_In_Next_7d tinyint default	0,'
||'Order_Sports_Added_In_Next_24hrs tinyint default	0,'
||'Order_Sports_Added_In_Last_24hrs tinyint default	0,'
||'Order_Sports_Added_In_Last_7d tinyint default	0,'
||'Order_Sports_Added_In_Last_30d tinyint default	0,'
||'Order_Sports_Added_In_Last_60d tinyint default	0,'
||'Order_Sports_Added_In_Last_90d tinyint default	0,'
||'Order_Sports_Added_In_Last_180d tinyint default	0,'
||'Order_Sports_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_Sports_Removed_Dt date default	null,'
||'Last_Order_Sports_Removed_Dt date default	null,'
||'Next_Order_Sports_Removed_Dt date default	null,'
||'Last_Order_Sports_Product_Removed varchar (80) default	null,'
||'Order_Sports_Removed_In_Next_60d tinyint default	0,'
||'Order_Sports_Removed_In_Next_30d tinyint default	0,'
||'Order_Sports_Removed_In_Next_7d tinyint default	0,'
||'Order_Sports_Removed_In_Next_24hrs tinyint default	0,'
||'Order_Sports_Removed_In_Last_24hrs tinyint default	0,'
||'Order_Sports_Removed_In_Last_7d tinyint default	0,'
||'Order_Sports_Removed_In_Last_30d tinyint default	0,'
||'Order_Sports_Removed_In_Last_60d tinyint default	0,'
||'Order_Sports_Removed_In_Last_90d tinyint default	0,'
||'Order_Sports_Removed_In_Last_180d tinyint default	0,'
||'Order_Sports_Removed_In_Last_1yr tinyint default	0,'
||'Order_FAMILY_Added_In_Next_30d tinyint default	0,'
||'Order_FAMILY_Added_In_Last_30d tinyint default	0,'
||'Order_BB_Unlimited_Added_In_Next_30d tinyint default	0,'
||'Order_BB_Unlimited_Added_In_Last_30d tinyint default	0,'
||'Order_BB_Lite_Added_In_Next_30d tinyint default	0,'
||'Order_BB_Lite_Added_In_Last_30d tinyint default	0,'
||'Order_BB_Fibre_Cap_Added_In_Next_30d tinyint default	0,'
||'Order_BB_Fibre_Cap_Added_In_Last_30d tinyint default	0,'
||'Order_BB_Fibre_Unlimited_Added_In_Next_30d tinyint default	0,'
||'Order_BB_Fibre_Unlimited_Added_In_Last_30d tinyint default	0,'
||'Order_BB_Fibre_Unlimited_Pro_Added_In_Next_30d tinyint default	0,'
||'Order_BB_Fibre_Unlimited_Pro_Added_In_Last_30d tinyint default	0,'
||'_1st_Order_MULTISCREEN_PLUS_Added_Dt date default	null,'
||'Last_Order_MULTISCREEN_PLUS_Added_Dt date default	null,'
||'Next_Order_MULTISCREEN_PLUS_Added_Dt date default	null,'
||'Last_Order_MULTISCREEN_PLUS_Product_Added varchar (80) default	null,'
||'Order_MULTISCREEN_PLUS_Added_In_Next_60d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Next_7d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Next_24hrs tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Last_24hrs tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Last_7d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Last_30d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Last_60d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Last_90d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Last_180d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_MULTISCREEN_PLUS_Removed_Dt date default	null,'
||'Last_Order_MULTISCREEN_PLUS_Removed_Dt date default	null,'
||'Next_Order_MULTISCREEN_PLUS_Removed_Dt date default	null,'
||'Last_Order_MULTISCREEN_PLUS_Product_Removed varchar (80) default	null,'
||'Order_MULTISCREEN_PLUS_Removed_In_Next_60d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Next_7d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Next_24hrs tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Last_24hrs tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Last_7d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Last_30d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Last_60d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Last_90d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Last_180d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Last_1yr tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Added_In_Next_30d tinyint default	0,'
||'Order_MULTISCREEN_PLUS_Removed_In_Next_30d tinyint default	0,'
||'Order_MULTISCREEN_Added_In_Next_60d tinyint default	0,'
||'Order_MULTISCREEN_Removed_In_Next_60d tinyint default	0,'
||'Order_SKY_MOBILE_HANDSET_Added_In_Next_30d tinyint default	0,'
||'Order_SKY_MOBILE_HANDSET_Added_In_Last_30d tinyint default	0,'
||'Order_SKY_MOBILE_HANDSET_Removed_In_Next_30d tinyint default	0,'
||'_1st_Order_SKY_MOBILE_TARIFFS_Added_Dt date default	null,'
||'Last_Order_SKY_MOBILE_TARIFFS_Added_Dt date default	null,'
||'Next_Order_SKY_MOBILE_TARIFFS_Added_Dt date default	null,'
||'Last_Order_SKY_MOBILE_TARIFFS_Product_Added varchar (80) default	null,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Next_60d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Next_30d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Next_7d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Next_24hrs tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Last_24hrs tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Last_7d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Last_30d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Last_60d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Last_90d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Last_180d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_SKY_MOBILE_TARIFFS_Removed_Dt date default	null,'
||'Last_Order_SKY_MOBILE_TARIFFS_Removed_Dt date default	null,'
||'Next_Order_SKY_MOBILE_TARIFFS_Removed_Dt date default	null,'
||'Last_Order_SKY_MOBILE_TARIFFS_Product_Removed varchar (80) default	null,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Next_60d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Next_30d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Next_7d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Next_24hrs tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Last_24hrs tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Last_7d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Last_30d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Last_60d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Last_90d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Last_180d tinyint default	0,'
||'Order_SKY_MOBILE_TARIFFS_Removed_In_Last_1yr tinyint default	0,'
||'SkyKids_Active tinyint default	0,'
||'SkyKids_Product_Holding varchar (80) default	null,'
||'SkyKids_Status_Code varchar (10) default	null,'
||'_1st_Order_KIDS_Added_Dt date default	null,'
||'Last_Order_KIDS_Added_Dt date default	null,'
||'Next_Order_KIDS_Added_Dt date default	null,'
||'Last_Order_KIDS_Product_Added varchar (80) default	null,'
||'Order_KIDS_Added_In_Next_60d tinyint default	0,'
||'Order_KIDS_Added_In_Next_30d tinyint default	0,'
||'Order_KIDS_Added_In_Next_7d tinyint default	0,'
||'Order_KIDS_Added_In_Next_24hrs tinyint default	0,'
||'Order_KIDS_Added_In_Last_24hrs tinyint default	0,'
||'Order_KIDS_Added_In_Last_7d tinyint default	0,'
||'Order_KIDS_Added_In_Last_30d tinyint default	0,'
||'Order_KIDS_Added_In_Last_60d tinyint default	0,'
||'Order_KIDS_Added_In_Last_90d tinyint default	0,'
||'Order_KIDS_Added_In_Last_180d tinyint default	0,'
||'Order_KIDS_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_KIDS_Removed_Dt date default	null,'
||'Last_Order_KIDS_Removed_Dt date default	null,'
||'Next_Order_KIDS_Removed_Dt date default	null,'
||'Last_Order_KIDS_Product_Removed varchar (80) default	null,'
||'Order_KIDS_Removed_In_Next_60d tinyint default	0,'
||'Order_KIDS_Removed_In_Next_30d tinyint default	0,'
||'Order_KIDS_Removed_In_Next_7d tinyint default	0,'
||'Order_KIDS_Removed_In_Next_24hrs tinyint default	0,'
||'Order_KIDS_Removed_In_Last_24hrs tinyint default	0,'
||'Order_KIDS_Removed_In_Last_7d tinyint default	0,'
||'Order_KIDS_Removed_In_Last_30d tinyint default	0,'
||'Order_KIDS_Removed_In_Last_60d tinyint default	0,'
||'Order_KIDS_Removed_In_Last_90d tinyint default	0,'
||'Order_KIDS_Removed_In_Last_180d tinyint default	0,'
||'Order_KIDS_Removed_In_Last_1yr tinyint default	0,'
||'_1st_Order_HD_BASIC_Added_Dt date default	null,'
||'Last_Order_HD_BASIC_Added_Dt date default	null,'
||'Next_Order_HD_BASIC_Added_Dt date default	null,'
||'Last_Order_HD_BASIC_Product_Added varchar (80) default	null,'
||'Order_HD_BASIC_Added_In_Next_60d tinyint default	0,'
||'Order_HD_BASIC_Added_In_Next_30d tinyint default	0,'
||'Order_HD_BASIC_Added_In_Next_7d tinyint default	0,'
||'Order_HD_BASIC_Added_In_Next_24hrs tinyint default	0,'
||'Order_HD_BASIC_Added_In_Last_24hrs tinyint default	0,'
||'Order_HD_BASIC_Added_In_Last_7d tinyint default	0,'
||'Order_HD_BASIC_Added_In_Last_30d tinyint default	0,'
||'Order_HD_BASIC_Added_In_Last_60d tinyint default	0,'
||'Order_HD_BASIC_Added_In_Last_90d tinyint default	0,'
||'Order_HD_BASIC_Added_In_Last_180d tinyint default	0,'
||'Order_HD_BASIC_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_HD_BASIC_Removed_Dt date default	null,'
||'Last_Order_HD_BASIC_Removed_Dt date default	null,'
||'Next_Order_HD_BASIC_Removed_Dt date default	null,'
||'Last_Order_HD_BASIC_Product_Removed varchar (80) default	null,'
||'Order_HD_BASIC_Removed_In_Next_60d tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Next_30d tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Next_7d tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Next_24hrs tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Last_24hrs tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Last_7d tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Last_30d tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Last_60d tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Last_90d tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Last_180d tinyint default	0,'
||'Order_HD_BASIC_Removed_In_Last_1yr tinyint default	0,'
||'_1st_Order_HD_PREMIUM_Added_Dt date default	null,'
||'Last_Order_HD_PREMIUM_Added_Dt date default	null,'
||'Next_Order_HD_PREMIUM_Added_Dt date default	null,'
||'Last_Order_HD_PREMIUM_Product_Added varchar (80) default	null,'
||'Order_HD_PREMIUM_Added_In_Next_60d tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Next_30d tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Next_7d tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Next_24hrs tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Last_24hrs tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Last_7d tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Last_30d tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Last_60d tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Last_90d tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Last_180d tinyint default	0,'
||'Order_HD_PREMIUM_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_HD_PREMIUM_Removed_Dt date default	null,'
||'Last_Order_HD_PREMIUM_Removed_Dt date default	null,'
||'Next_Order_HD_PREMIUM_Removed_Dt date default	null,'
||'Last_Order_HD_PREMIUM_Product_Removed varchar (80) default	null,'
||'Order_HD_PREMIUM_Removed_In_Next_60d tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Next_30d tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Next_7d tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Next_24hrs tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Last_24hrs tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Last_7d tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Last_30d tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Last_60d tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Last_90d tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Last_180d tinyint default	0,'
||'Order_HD_PREMIUM_Removed_In_Last_1yr tinyint default	0,'
||'_1st_Order_BOXSETS_Added_Dt date default	null,'
||'Last_Order_BOXSETS_Added_Dt date default	null,'
||'Next_Order_BOXSETS_Added_Dt date default	null,'
||'Last_Order_BOXSETS_Product_Added varchar (80) default	null,'
||'Order_BOXSETS_Added_In_Next_60d tinyint default	0,'
||'Order_BOXSETS_Added_In_Next_30d tinyint default	0,'
||'Order_BOXSETS_Added_In_Next_7d tinyint default	0,'
||'Order_BOXSETS_Added_In_Next_24hrs tinyint default	0,'
||'Order_BOXSETS_Added_In_Last_24hrs tinyint default	0,'
||'Order_BOXSETS_Added_In_Last_7d tinyint default	0,'
||'Order_BOXSETS_Added_In_Last_30d tinyint default	0,'
||'Order_BOXSETS_Added_In_Last_60d tinyint default	0,'
||'Order_BOXSETS_Added_In_Last_90d tinyint default	0,'
||'Order_BOXSETS_Added_In_Last_180d tinyint default	0,'
||'Order_BOXSETS_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_BOXSETS_Removed_Dt date default	null,'
||'Last_Order_BOXSETS_Removed_Dt date default	null,'
||'Next_Order_BOXSETS_Removed_Dt date default	null,'
||'Last_Order_BOXSETS_Product_Removed varchar (80) default	null,'
||'Order_BOXSETS_Removed_In_Next_60d tinyint default	0,'
||'Order_BOXSETS_Removed_In_Next_30d tinyint default	0,'
||'Order_BOXSETS_Removed_In_Next_7d tinyint default	0,'
||'Order_BOXSETS_Removed_In_Next_24hrs tinyint default	0,'
||'Order_BOXSETS_Removed_In_Last_24hrs tinyint default	0,'
||'Order_BOXSETS_Removed_In_Last_7d tinyint default	0,'
||'Order_BOXSETS_Removed_In_Last_30d tinyint default	0,'
||'Order_BOXSETS_Removed_In_Last_60d tinyint default	0,'
||'Order_BOXSETS_Removed_In_Last_90d tinyint default	0,'
||'Order_BOXSETS_Removed_In_Last_180d tinyint default	0,'
||'Order_BOXSETS_Removed_In_Last_1yr tinyint default	0,'
||'_1st_Order_UOD_Added_Dt date default	null,'
||'Last_Order_UOD_Added_Dt date default	null,'
||'Next_Order_UOD_Added_Dt date default	null,'
||'Last_Order_UOD_Product_Added varchar (80) default	null,'
||'Order_UOD_Added_In_Next_60d tinyint default	0,'
||'Order_UOD_Added_In_Next_30d tinyint default	0,'
||'Order_UOD_Added_In_Next_7d tinyint default	0,'
||'Order_UOD_Added_In_Next_24hrs tinyint default	0,'
||'Order_UOD_Added_In_Last_24hrs tinyint default	0,'
||'Order_UOD_Added_In_Last_7d tinyint default	0,'
||'Order_UOD_Added_In_Last_30d tinyint default	0,'
||'Order_UOD_Added_In_Last_60d tinyint default	0,'
||'Order_UOD_Added_In_Last_90d tinyint default	0,'
||'Order_UOD_Added_In_Last_180d tinyint default	0,'
||'Order_UOD_Added_In_Last_1yr tinyint default	0,'
||'_1st_Order_UOD_Removed_Dt date default	null,'
||'Last_Order_UOD_Removed_Dt date default	null,'
||'Next_Order_UOD_Removed_Dt date default	null,'
||'Last_Order_UOD_Product_Removed varchar (80) default	null,'
||'Order_UOD_Removed_In_Next_60d tinyint default	0,'
||'Order_UOD_Removed_In_Next_30d tinyint default	0,'
||'Order_UOD_Removed_In_Next_7d tinyint default	0,'
||'Order_UOD_Removed_In_Next_24hrs tinyint default	0,'
||'Order_UOD_Removed_In_Last_24hrs tinyint default	0,'
||'Order_UOD_Removed_In_Last_7d tinyint default	0,'
||'Order_UOD_Removed_In_Last_30d tinyint default	0,'
||'Order_UOD_Removed_In_Last_60d tinyint default	0,'
||'Order_UOD_Removed_In_Last_90d tinyint default	0,'
||'Order_UOD_Removed_In_Last_180d tinyint default	0,'
||'Order_UOD_Removed_In_Last_1yr tinyint default	0,'
||'Up_Handset tinyint default	0,'
||'Up_Mobile tinyint default	0,'
||'party_id varchar (50) default	null,'
||'owning_cust_account_id varchar (50) default	null,'
||'credit_tier_code varchar (20) default	null,'
||'cb_key_household_mdu bigint default	null,'
||'VIP_STATUS varchar (50) default	null,'
||'EXPERIAN_FACTOR1_DEC int default	null,'
||'EXPERIAN_FACTOR2_DEC int default	null,'
||'EXPERIAN_FACTOR3_DEC int default	null,'
||'EXPERIAN_FACTOR4_DEC int default	null,'
||'EXPERIAN_FACTOR5_DEC int default	null,'
||'EXPERIAN_FACTOR6_DEC int default	null,'
||'prev_fbp_count int default	0,'
||'h_delphi_band varchar (40) default	null,'
||'sky_core_affordability_score varchar (40) default	null,'
||'sky_mobile_affordability_score varchar (50) default	null,'
||'row_id bigint default autoincrement,'
||'update_Dt datetime default	null'

*/